# Generated by Django 2.2.24 on 2021-07-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200, verbose_name='主机名')),
                ('host_ip', models.CharField(max_length=200, verbose_name='IP地址')),
                ('host_user', models.CharField(max_length=200, verbose_name='用户名')),
                ('host_password', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='密码')),
                ('host_port', models.IntegerField(default=22, verbose_name='端口')),
                ('host_key_file', models.FileField(blank=True, null=True, upload_to='key_file', verbose_name='密钥')),
                ('domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='域名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '主机列表',
                'verbose_name_plural': '主机列表',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=10)),
                ('t2', models.CharField(max_length=10)),
                ('num', models.IntegerField(default=0, max_length=50)),
            ],
        ),
    ]
