# Generated by Django 2.2.5 on 2021-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
                ('host_user', models.CharField(max_length=200)),
                ('host_password', models.CharField(default='', max_length=200, null=True)),
                ('host_port', models.IntegerField(default=22)),
                ('host_key_file', models.CharField(max_length=200, null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
