# Generated by Django 2.2.24 on 2021-07-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_status', models.IntegerField(default=0, verbose_name='主机状态')),
                ('install_server', models.CharField(max_length=200, verbose_name='安装服务')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.HostList')),
            ],
        ),
    ]
