# Generated by Django 2.2.5 on 2021-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='host_key_file',
            field=models.FileField(null=True, upload_to='key_file'),
        ),
    ]
