# Generated by Django 3.2 on 2021-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='host_password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
