# Generated by Django 3.2 on 2021-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='host_key_file',
            field=models.FileField(blank=True, null=True, upload_to='key_file'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='host_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
