# Generated by Django 3.2 on 2021-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0002_hostlist_host_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
