# Generated by Django 4.0.5 on 2022-06-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0002_installserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_path', models.CharField(max_length=200, verbose_name='目标路径')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.hostlist')),
            ],
        ),
    ]
