# Generated by Django 4.0.5 on 2022-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0003_deployhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='des_path',
            field=models.CharField(max_length=200, null=True, verbose_name='目标路径'),
        ),
        migrations.DeleteModel(
            name='DeployHost',
        ),
    ]
